In [9]:
### Importing libraries

import git
import os
import pandas as pd
import numpy as np
import json
from pathlib import Path
import mysql.connector as mc
import os
from dotenv import load_dotenv
from sqlalchemy import create_engine,text
from urllib.parse import quote_plus

In [2]:
## Setting up folder paths for input or output
processed_data_path=r'C:\Users\nagan\OneDrive\Desktop\Guvi\Project\PhonePe\Data Processing\Files\Processed_Data'
output_path=r"C:\Users\nagan\OneDrive\Desktop\Guvi\Project\PhonePe\Data Processing\Files\GitHub_Raw_Data"

In [27]:
### Cloning git repository
git_url="https://github.com/PhonePe/pulse.git"
git.Repo.clone_from(git_url,output_path)
print('Repository Cloned Successfully')

Repository Cloned Successfully

### Aggregated Transaction Data

In [60]:
### settingup the path and readign all the files present in folder

## this is for aggregated transaction data

# folder_path=r"C:\Users\nagan\OneDrive\Desktop\Guvi\Project\PhonePe\Data Processing\Files\GitHub_Raw_Data\data\aggregated\transaction\country\india\state"
folder_path=output_path+"/data/aggregated/transaction/country/india/state/"
agg_state_list=os.listdir(folder_path)
agg_state_list[:10]

# print(folder_path)

########## Creatign Dictionary to store only required columns from all the file using for loop


data_dict={'State':[],'Year':[],'Quarter':[],'Transaction_Type':[],'Transaction_Count':[],'Transaction_Amount':[]}

## Looping through all the folders and files for each state

for i in agg_state_list: #  here i is state folder
    year_path=folder_path+i+"/"
    agg_yrs=os.listdir(year_path) # this list ill have all the years for each state data
    # print(agg_yrs)

    for year in agg_yrs:
        file_path=year_path+year+"/"  ## path for all the files present in the state folder
        agg_files=os.listdir(file_path)

        # print(agg_files)
        for k in agg_files:
            json_file=file_path+k  ## json file path
            # print(file)
            data=open(json_file,'r')
            d=json.load(data)
            for z in d['data']['transactionData']:
                Name=z['name']
                count=z['paymentInstruments'][0]['count']
                amount=z['paymentInstruments'][0]['amount']
                data_dict['Transaction_Type'].append(Name) #appending type amount and count to defined dictionary
                data_dict['Transaction_Count'].append(count)
                data_dict['Transaction_Amount'].append(amount)
                data_dict['State'].append(i)
                data_dict['Year'].append(year)
                data_dict['Quarter'].append(int(k.strip('.json')))


## creating the dataframe
agg_df=pd.DataFrame(data_dict)

display(agg_df)

#writing it to csv
agg_df.to_csv(f"{processed_data_path+'/'}aggregated_transaction_data.csv",index=False)

#### Aggregated Insurance Data

In [65]:
### settingup the path and readign all the files present in folder

## this is for aggregated insurance data

# folder_path=r"C:\Users\nagan\OneDrive\Desktop\Guvi\Project\PhonePe\Data Processing\Files\GitHub_Raw_Data\data\aggregated\transaction\country\india\state"
folder_path=output_path+"/data/aggregated/insurance/country/india/state/"
agg_state_list=os.listdir(folder_path)
agg_state_list[:10]

# print(folder_path)

########## Creatign Dictionary to store only required columns from all the file using for loop


data_dict={'State':[],'Year':[],'Quarter':[],'Insurance_Type':[],'Insurance_Count':[],'Insurance_Amount':[]}

## Looping through all the folders and files for each state

for i in agg_state_list: #  here i is state folder
    year_path=folder_path+i+"/"
    agg_yrs=os.listdir(year_path) # this list ill have all the years for each state data
    # print(agg_yrs)

    for year in agg_yrs:
        file_path=year_path+year+"/"  ## path for all the files present in the state folder
        agg_files=os.listdir(file_path)

        # print(agg_files)
        for k in agg_files:
            json_file=file_path+k  ## json file path
            # print(file)
            data=open(json_file,'r')
            d=json.load(data)
            for z in d['data']['transactionData']:
                Name=z['name']
                # type=z['paymentInstruments'][0]['type']
                count=z['paymentInstruments'][0]['count']
                amount=z['paymentInstruments'][0]['amount']
                data_dict['Insurance_Type'].append(Name) #appending type amount and count to defined dictionary
                data_dict['Insurance_Count'].append(count)
                data_dict['Insurance_Amount'].append(amount)
                data_dict['State'].append(i)
                data_dict['Year'].append(year)
                data_dict['Quarter'].append(int(k.strip('.json')))


## creating the dataframe
agg_df=pd.DataFrame(data_dict)

display(agg_df.head())

#writing it to csv
agg_df.to_csv(f"{processed_data_path+'/'}aggregated_insurance_data.csv",index=False)

,State,Year,Quarter,Insurance_Type,Insurance_Count,Insurance_Amount
0,andaman-&-nicobar-islands,2020,2,Insurance,6,1360.0
1,andaman-&-nicobar-islands,2020,3,Insurance,41,15380.0
2,andaman-&-nicobar-islands,2020,4,Insurance,124,157975.0
3,andaman-&-nicobar-islands,2021,1,Insurance,225,244266.0
4,andaman-&-nicobar-islands,2021,2,Insurance,137,181504.0

#### Aggregated users

In [94]:
### settingup the path and readign all the files present in folder

## this is for aggregated User data

# folder_path=r"C:\Users\nagan\OneDrive\Desktop\Guvi\Project\PhonePe\Data Processing\Files\GitHub_Raw_Data\data\aggregated\transaction\country\india\state"
folder_path=output_path+"/data/aggregated/user/country/india/state/"
agg_state_list=os.listdir(folder_path)
# agg_state_list[:10]

# print(folder_path)
# Data Processing\Files\GitHub_Raw_Data\data\aggregated\user\country\india\state

null_files = []   ### list to store files with null or missing data

########## Creatign Dictionary to store only required columns from all the file using for loop


data_dict={'State':[],'Year':[],'Quarter':[],'User_Brand':[],'User_Registrd_Count':[],'User_Percentage':[]}

## Looping through all the folders and files for each state

for i in agg_state_list: #  here i is state folder
    year_path=folder_path+i+"/"
    agg_yrs=os.listdir(year_path) # this list ill have all the years for each state data
    # print(agg_yrs)

    for year in agg_yrs:
        file_path=year_path+year+"/"  ## path for all the files present in the state folder
        agg_files=os.listdir(file_path)

        # print(agg_files)
        for k in agg_files:
            json_file=file_path+k  ## json file path
            # print(file)
            data=open(json_file,'r')
            d=json.load(data)

            # print(d)
            if (d.get('data') is None) or ('usersByDevice' not in d['data']) or (d['data']['usersByDevice'] is None):
                # print(f"⚠️ No data in file: {json_file}")
                null_files.append(json_file)
                
                data_dict['User_Brand'].append(None)
                data_dict['User_Registrd_Count'].append(0)
                data_dict['User_Percentage'].append(0)
                data_dict['State'].append(i)
                data_dict['Year'].append(year)
                data_dict['Quarter'].append(int(k.strip('.json')))

                continue
                 
            # json_path = Path(json_file)
            # with json_path.open('r', encoding='utf-8') as fh:
            #     d = json.load(fh)
            for z in d['data']['usersByDevice']:
                # print(z)
                brand=z['brand']
                count=z['count']
                amount=z['percentage']
                data_dict['User_Brand'].append(brand) #appending type amount and count to defined dictionary
                data_dict['User_Registrd_Count'].append(count)
                data_dict['User_Percentage'].append(amount)
                data_dict['State'].append(i)
                data_dict['Year'].append(year)
                data_dict['Quarter'].append(int(k.strip('.json')))


## creating the dataframe
agg_df=pd.DataFrame(data_dict)

display(agg_df.head())

#writing it to csv
agg_df.to_csv(f"{processed_data_path+'/'}aggregated_user_data.csv",index=False)

,State,Year,Quarter,User_Brand,User_Registrd_Count,User_Percentage
0,andaman-&-nicobar-islands,2018,1,Xiaomi,1665,0.247033
1,andaman-&-nicobar-islands,2018,1,Samsung,1445,0.214392
2,andaman-&-nicobar-islands,2018,1,Vivo,982,0.145697
3,andaman-&-nicobar-islands,2018,1,Oppo,501,0.074332
4,andaman-&-nicobar-islands,2018,1,OnePlus,332,0.049258

In [92]:
agg_df['User_Brand'].unique()

array(['Xiaomi', 'Samsung', 'Vivo', 'Oppo', 'OnePlus', 'Realme', 'Apple',
       'Motorola', 'Lenovo', 'Huawei', 'Others', 'Tecno', None, 'Gionee',
       'Infinix', 'Asus', 'Micromax', 'HMD Global', 'Lava', 'COOLPAD',
       'Lyf'], dtype=object)

## Map Data Processing

#### Map Data Transaction

In [96]:
### settingup the path and readign all the files present in folder

## this is for aggregated transaction data

# folder_path=r"C:\Users\nagan\OneDrive\Desktop\Guvi\Project\PhonePe\Data Processing\Files\GitHub_Raw_Data\data\aggregated\transaction\country\india\state"
folder_path=output_path+"/data/map/transaction/hover/country/india/state/"
agg_state_list=os.listdir(folder_path)
agg_state_list[:10]

channel='map'
data_type='transaction'

# print(folder_path)

########## Creatign Dictionary to store only required columns from all the file using for loop


data_dict={'State':[],'Year':[],'Quarter':[],'District_Name':[],'Transaction_Count':[],'Transaction_Amount':[]}

## Looping through all the folders and files for each state

for i in agg_state_list: #  here i is state folder
    year_path=folder_path+i+"/"
    agg_yrs=os.listdir(year_path) # this list ill have all the years for each state data
    # print(agg_yrs)

    for year in agg_yrs:
        file_path=year_path+year+"/"  ## path for all the files present in the state folder
        agg_files=os.listdir(file_path)

        # print(agg_files)
        for k in agg_files:
            json_file=file_path+k  ## json file path
            # print(file)
            data=open(json_file,'r')
            d=json.load(data)
            for z in d['data']['hoverDataList']:
                Name=z['name']
                count=z['metric'][0]['count']
                amount=z['metric'][0]['amount']
                data_dict['District_Name'].append(Name) #appending type amount and count to defined dictionary
                data_dict['Transaction_Count'].append(count)
                data_dict['Transaction_Amount'].append(amount)
                data_dict['State'].append(i)
                data_dict['Year'].append(year)
                data_dict['Quarter'].append(int(k.strip('.json')))


## creating the dataframe
agg_df=pd.DataFrame(data_dict)

display(agg_df)

#writing it to csv
agg_df.to_csv(f"{processed_data_path+'/'}{channel}_{data_type}_data.csv",index=False)

,State,Year,Quarter,District_Name,Transaction_Count,Transaction_Amount
0,andaman-&-nicobar-islands,2018,1,north and middle andaman district,442,9.316631e+05
1,andaman-&-nicobar-islands,2018,1,south andaman district,5688,1.256025e+07
2,andaman-&-nicobar-islands,2018,1,nicobars district,528,1.139849e+06
3,andaman-&-nicobar-islands,2018,2,north and middle andaman district,825,1.317863e+06
4,andaman-&-nicobar-islands,2018,2,south andaman district,9395,2.394824e+07
...,...,...,...,...,...,...
20599,west-bengal,2024,4,alipurduar district,15875637,2.099251e+10
20600,west-bengal,2024,4,paschim bardhaman district,56616799,6.968735e+10
20601,west-bengal,2024,4,nadia district,65274337,1.079320e+11
20602,west-bengal,2024,4,birbhum district,36905213,5.778701e+10
20603,west-bengal,2024,4,purba medinipur district,67833775,1.142771e+11

#### Map Insurance Data

In [99]:
### settingup the path and readign all the files present in folder

## this is for aggregated transaction data

# folder_path=r"C:\Users\nagan\OneDrive\Desktop\Guvi\Project\PhonePe\Data Processing\Files\GitHub_Raw_Data\data\aggregated\transaction\country\india\state"
folder_path=output_path+"/data/map/insurance/hover/country/india/state/"
agg_state_list=os.listdir(folder_path)
agg_state_list[:10]

channel='map'
data_type='insurance'

# print(folder_path)

########## Creatign Dictionary to store only required columns from all the file using for loop


data_dict={'State':[],'Year':[],'Quarter':[],'District_Name':[],'Insurance_Count':[],'Insurance_Amount':[]}

## Looping through all the folders and files for each state

for i in agg_state_list: #  here i is state folder
    year_path=folder_path+i+"/"
    agg_yrs=os.listdir(year_path) # this list ill have all the years for each state data
    # print(agg_yrs)

    for year in agg_yrs:
        file_path=year_path+year+"/"  ## path for all the files present in the state folder
        agg_files=os.listdir(file_path)

        # print(agg_files)
        for k in agg_files:
            json_file=file_path+k  ## json file path
            # print(file)
            data=open(json_file,'r')
            d=json.load(data)
            for z in d['data']['hoverDataList']:
                Name=z['name']
                # type=z['paymentInstruments'][0]['type']
                count=z['metric'][0]['count']
                amount=z['metric'][0]['amount']
                data_dict['District_Name'].append(Name) #appending type amount and count to defined dictionary
                data_dict['Insurance_Count'].append(count)
                data_dict['Insurance_Amount'].append(amount)
                data_dict['State'].append(i)
                data_dict['Year'].append(year)
                data_dict['Quarter'].append(int(k.strip('.json')))

## creating the dataframe
agg_df=pd.DataFrame(data_dict)

display(agg_df)

#writing it to csv
agg_df.to_csv(f"{processed_data_path+'/'}{channel}_{data_type}_data.csv",index=False)

,State,Year,Quarter,District_Name,Insurance_Count,Insurance_Amount
0,andaman-&-nicobar-islands,2020,2,south andaman district,3,795.0
1,andaman-&-nicobar-islands,2020,2,nicobars district,3,565.0
2,andaman-&-nicobar-islands,2020,3,north and middle andaman district,1,281.0
3,andaman-&-nicobar-islands,2020,3,south andaman district,35,13651.0
4,andaman-&-nicobar-islands,2020,3,nicobars district,5,1448.0
...,...,...,...,...,...,...
13871,west-bengal,2024,4,alipurduar district,1023,1613143.0
13872,west-bengal,2024,4,paschim bardhaman district,4945,7005851.0
13873,west-bengal,2024,4,nadia district,3807,5031294.0
13874,west-bengal,2024,4,birbhum district,1818,2423290.0
13875,west-bengal,2024,4,purba medinipur district,3559,4439061.0

#### Map User Data

In [117]:
### settingup the path and readign all the files present in folder

## this is for aggregated transaction data

# folder_path=r"C:\Users\nagan\OneDrive\Desktop\Guvi\Project\PhonePe\Data Processing\Files\GitHub_Raw_Data\data\aggregated\transaction\country\india\state"
folder_path=output_path+"/data/map/user/hover/country/india/state/"
agg_state_list=os.listdir(folder_path)

channel='map'
data_type='user'

# print(folder_path)

########## Creatign Dictionary to store only required columns from all the file using for loop


data_dict={'State':[],'Year':[],'Quarter':[],'User_District_Name':[],'User_Registrd_Count':[],'User_App_Opens':[]}

## Looping through all the folders and files for each state

for i in agg_state_list: #  here i is state folder
    year_path=folder_path+i+"/"
    agg_yrs=os.listdir(year_path) # this list ill have all the years for each state data
    # print(agg_yrs)

    for year in agg_yrs:
        file_path=year_path+year+"/"  ## path for all the files present in the state folder
        agg_files=os.listdir(file_path)

        # print(agg_files)
        for k in agg_files:
            json_file=file_path+k  ## json file path
            # print(file)
            data=open(json_file,'r')
            d=json.load(data)
            for district,info in d['data']['hoverData'].items():
                Name=district

                # print(z)
                # print(z)
                # # type=z['paymentInstruments'][0]['type']
                count=info['registeredUsers']
                amount=info['appOpens']
                # print(Name,count,amount)
                # print(year)
                data_dict['User_District_Name'].append(Name) #appending type amount and count to defined dictionary
                data_dict['User_Registrd_Count'].append(count)
                data_dict['User_App_Opens'].append(amount)
                data_dict['State'].append(i)
                data_dict['Year'].append(year)
                data_dict['Quarter'].append(int(k.strip('.json')))

## creating the dataframe
agg_df=pd.DataFrame(data_dict)

display(agg_df)

#writing it to csv
agg_df.to_csv(f"{processed_data_path+'/'}{channel}_{data_type}_data.csv",index=False)

,State,Year,Quarter,User_District_Name,User_Registrd_Count,User_App_Opens
0,andaman-&-nicobar-islands,2018,1,north and middle andaman district,632,0
1,andaman-&-nicobar-islands,2018,1,south andaman district,5846,0
2,andaman-&-nicobar-islands,2018,1,nicobars district,262,0
3,andaman-&-nicobar-islands,2018,2,north and middle andaman district,911,0
4,andaman-&-nicobar-islands,2018,2,south andaman district,8143,0
...,...,...,...,...,...,...
20603,west-bengal,2024,4,alipurduar district,475688,31842355
20604,west-bengal,2024,4,paschim bardhaman district,1468252,80543469
20605,west-bengal,2024,4,nadia district,1861738,98740305
20606,west-bengal,2024,4,birbhum district,1114220,73465525
20607,west-bengal,2024,4,purba medinipur district,1717074,108350777

## Top Data Processing

### Top Transaction Data

In [160]:
### settingup the path and readign all the files present in folder

## this is for transaction data

# folder_path=r"C:\Users\nagan\OneDrive\Desktop\Guvi\Project\PhonePe\Data Processing\Files\GitHub_Raw_Data\data\aggregated\transaction\country\india\state"
folder_path=output_path+"/data/top/transaction/country/india/state/"
agg_state_list=os.listdir(folder_path)
agg_state_list[:10]

channel='top'
data_type='transaction'

# print(folder_path)

########## Creating Dictionary to store only required columns from all the file using for loop


data_dict={'State':[],'Year':[],'Quarter':[],'Level':[],'District_Pincode_Name':[],'Transaction_Count':[],'Transaction_Amount':[]}

## Looping through all the folders and files for each state

for i in agg_state_list: #  here i is state folder
    year_path=folder_path+i+"/"
    agg_yrs=os.listdir(year_path) # this list ill have all the years for each state data
    # print(agg_yrs)

    for year in agg_yrs:
        file_path=year_path+year+"/"  ## path for all the files present in the state folder
        agg_files=os.listdir(file_path)

        # print(agg_files)
        for k in agg_files:
            json_file=file_path+k  ## json file path
            # print(file)
            data=open(json_file,'r')
            d=json.load(data)

            ### district level data
            for z in d['data']['districts']:
                # print(z)
                Name=z['entityName']
                count=z['metric']['count']
                amount=z['metric']['amount']
                # print(Name,count,amount)
                # print(year)
                data_dict['Level'].append('District')
                data_dict['District_Pincode_Name'].append(Name) #appending type amount and count to defined dictionary
                data_dict['Transaction_Count'].append(count)
                data_dict['Transaction_Amount'].append(amount)
                data_dict['State'].append(i)
                data_dict['Year'].append(year)
                data_dict['Quarter'].append(int(k.strip('.json')))
            
            ## for pincode level data
            for z in d['data']['pincodes']:
                # print(z)
                Name=z['entityName']
                count=z['metric']['count']
                amount=z['metric']['amount']
                # print(Name,count,amount)
                # print(year)
                data_dict['Level'].append('Pincode')
                data_dict['District_Pincode_Name'].append(Name) #appending type amount and count to defined dictionary
                data_dict['Transaction_Count'].append(count)
                data_dict['Transaction_Amount'].append(amount)
                data_dict['State'].append(i)
                data_dict['Year'].append(year)
                data_dict['Quarter'].append(int(k.strip('.json')))


### For State Level Files
folder_path_st_lvl=output_path+"/data/top/transaction/country/india/"

years_list=['2018','2019','2020','2021','2022','2023','2024']

for i in years_list:
    file_path=folder_path_st_lvl+i+"/"
    # print(file_path)

    agg_files=os.listdir(file_path)
    for k in agg_files:
            json_file=file_path+k  ## json file path
            # print(json_file)
            # print(file)
            data=open(json_file,'r')
            d=json.load(data)  
            # print(d)
        ### State level data
            for z in d['data']['states']:
                # print(z)
                Name=z['entityName']
                count=z['metric']['count']
                amount=z['metric']['amount']
                # print(Name,count,amount)
                # print(year)
                data_dict['Level'].append('State')
                data_dict['District_Pincode_Name'].append(Name) #appending type amount and count to defined dictionary
                data_dict['Transaction_Count'].append(count)
                data_dict['Transaction_Amount'].append(amount)
                data_dict['State'].append(Name)
                data_dict['Year'].append(year)
                data_dict['Quarter'].append(int(k.strip('.json')))


## creating the dataframe
agg_df=pd.DataFrame(data_dict)

display(agg_df)

# #writing it to csv
agg_df.to_csv(f"{processed_data_path+'/'}{channel}_{data_type}_data.csv",index=False)

,State,Year,Quarter,Level,District_Pincode_Name,Transaction_Count,Transaction_Amount
0,andaman-&-nicobar-islands,2018,1,District,south andaman,5688,1.256025e+07
1,andaman-&-nicobar-islands,2018,1,District,nicobars,528,1.139849e+06
2,andaman-&-nicobar-islands,2018,1,District,north and middle andaman,442,9.316631e+05
3,andaman-&-nicobar-islands,2018,1,Pincode,744101,1622,2.769298e+06
4,andaman-&-nicobar-islands,2018,1,Pincode,744103,1223,2.238042e+06
...,...,...,...,...,...,...,...
18570,rajasthan,2024,4,State,rajasthan,2043469547,2.793049e+12
18571,madhya pradesh,2024,4,State,madhya pradesh,1685401835,2.003305e+12
18572,bihar,2024,4,State,bihar,1559667675,2.098927e+12
18573,west bengal,2024,4,State,west bengal,1227135682,1.810100e+12
18574,odisha,2024,4,State,odisha,1143097568,1.305458e+12

### Top Insurance Data

In [163]:
### settingup the path and readign all the files present in folder

## this is for transaction data

# folder_path=r"C:\Users\nagan\OneDrive\Desktop\Guvi\Project\PhonePe\Data Processing\Files\GitHub_Raw_Data\data\aggregated\transaction\country\india\state"
folder_path=output_path+"/data/top/insurance/country/india/state/"
agg_state_list=os.listdir(folder_path)
agg_state_list[:10]

channel='top'
data_type='insurance'

# print(folder_path)

########## Creating Dictionary to store only required columns from all the file using for loop


data_dict={'State':[],'Year':[],'Quarter':[],'Level':[],'District_Pincode_Name':[],'Transaction_Count':[],'Transaction_Amount':[]}

## Looping through all the folders and files for each state

for i in agg_state_list: #  here i is state folder
    year_path=folder_path+i+"/"
    agg_yrs=os.listdir(year_path) # this list ill have all the years for each state data
    # print(agg_yrs)

    for year in agg_yrs:
        file_path=year_path+year+"/"  ## path for all the files present in the state folder
        agg_files=os.listdir(file_path)

        # print(agg_files)
        for k in agg_files:
            json_file=file_path+k  ## json file path
            # print(file)
            data=open(json_file,'r')
            d=json.load(data)

            ### district level data
            for z in d['data']['districts']:
                # print(z)
                Name=z['entityName']
                count=z['metric']['count']
                amount=z['metric']['amount']
                # print(Name,count,amount)
                # print(year)
                data_dict['Level'].append('District')
                data_dict['District_Pincode_Name'].append(Name) #appending type amount and count to defined dictionary
                data_dict['Transaction_Count'].append(count)
                data_dict['Transaction_Amount'].append(amount)
                data_dict['State'].append(i)
                data_dict['Year'].append(year)
                data_dict['Quarter'].append(int(k.strip('.json')))
            
            ## for pincode level data
            for z in d['data']['pincodes']:
                # print(z)
                Name=z['entityName']
                count=z['metric']['count']
                amount=z['metric']['amount']
                # print(Name,count,amount)
                # print(year)
                data_dict['Level'].append('Pincode')
                data_dict['District_Pincode_Name'].append(Name) #appending type amount and count to defined dictionary
                data_dict['Transaction_Count'].append(count)
                data_dict['Transaction_Amount'].append(amount)
                data_dict['State'].append(i)
                data_dict['Year'].append(year)
                data_dict['Quarter'].append(int(k.strip('.json')))


### For State Level Files
folder_path_st_lvl=output_path+"/data/top/insurance/country/india/"

years_list=['2018','2019','2020','2021','2022','2023','2024']

for i in years_list:
    file_path=folder_path_st_lvl+i+"/"
    # print(file_path)
    try:
        agg_files=os.listdir(file_path)
        for k in agg_files:
                json_file=file_path+k  ## json file path
                # print(json_file)
                # print(file)
                data=open(json_file,'r')
                d=json.load(data)  
                # print(d)
            ### State level data
                for z in d['data']['states']:
                    # print(z)
                    Name=z['entityName']
                    count=z['metric']['count']
                    amount=z['metric']['amount']
                    # print(Name,count,amount)
                    # print(year)
                    data_dict['Level'].append('State')
                    data_dict['District_Pincode_Name'].append(Name) #appending type amount and count to defined dictionary
                    data_dict['Transaction_Count'].append(count)
                    data_dict['Transaction_Amount'].append(amount)
                    data_dict['State'].append(Name)
                    data_dict['Year'].append(year)
                    data_dict['Quarter'].append(int(k.strip('.json')))
    except Exception as e:
        print('Error found',e)


## creating the dataframe
agg_df=pd.DataFrame(data_dict)

display(agg_df)

# #writing it to csv
agg_df.to_csv(f"{processed_data_path+'/'}{channel}_{data_type}_data.csv",index=False)

Error found [WinError 3] The system cannot find the path specified: 'C:\\Users\\nagan\\OneDrive\\Desktop\\Guvi\\Project\\PhonePe\\Data Processing\\Files\\GitHub_Raw_Data/data/top/insurance/country/india/2018/'
Error found [WinError 3] The system cannot find the path specified: 'C:\\Users\\nagan\\OneDrive\\Desktop\\Guvi\\Project\\PhonePe\\Data Processing\\Files\\GitHub_Raw_Data/data/top/insurance/country/india/2019/'

,State,Year,Quarter,Level,District_Pincode_Name,Transaction_Count,Transaction_Amount
0,andaman-&-nicobar-islands,2020,2,District,nicobars,3,565.0
1,andaman-&-nicobar-islands,2020,2,District,south andaman,3,795.0
2,andaman-&-nicobar-islands,2020,2,Pincode,744301,3,565.0
3,andaman-&-nicobar-islands,2020,2,Pincode,744104,2,513.0
4,andaman-&-nicobar-islands,2020,2,Pincode,744101,1,282.0
...,...,...,...,...,...,...,...
12461,kerala,2024,4,State,kerala,89533,144083113.0
12462,telangana,2024,4,State,telangana,78498,124755619.0
12463,rajasthan,2024,4,State,rajasthan,73530,127930986.0
12464,delhi,2024,4,State,delhi,67962,94390728.0
12465,bihar,2024,4,State,bihar,62662,83739800.0

### Top User Data

In [168]:
### settingup the path and readign all the files present in folder

## this is for transaction data

# folder_path=r"C:\Users\nagan\OneDrive\Desktop\Guvi\Project\PhonePe\Data Processing\Files\GitHub_Raw_Data\data\aggregated\transaction\country\india\state"
folder_path=output_path+"/data/top/user/country/india/state/"
agg_state_list=os.listdir(folder_path)
agg_state_list[:10]

channel='top'
data_type='user'

# print(folder_path)

########## Creating Dictionary to store only required columns from all the file using for loop

# 'User_District_Name':[],'User_Registrd_Count':[],'User_App_Opens':[]}

data_dict={'State':[],'Year':[],'Quarter':[],'Level':[],'District_Pincode_Name':[],'User_Registrd_Count':[]}

## Looping through all the folders and files for each state

for i in agg_state_list: #  here i is state folder
    year_path=folder_path+i+"/"
    agg_yrs=os.listdir(year_path) # this list ill have all the years for each state data
    # print(agg_yrs)

    for year in agg_yrs:
        file_path=year_path+year+"/"  ## path for all the files present in the state folder
        agg_files=os.listdir(file_path)

        # print(agg_files)
        for k in agg_files:
            json_file=file_path+k  ## json file path
            # print(file)
            data=open(json_file,'r')
            d=json.load(data)

            ### district level data
            for z in d['data']['districts']:
                # print(z)
                Name=z['name']
                count=z['registeredUsers']
                # print(Name,count,amount)
                # print(year)
                data_dict['Level'].append('District')
                data_dict['District_Pincode_Name'].append(Name) #appending type amount and count to defined dictionary
                data_dict['User_Registrd_Count'].append(count)
                data_dict['State'].append(i)
                data_dict['Year'].append(year)
                data_dict['Quarter'].append(int(k.strip('.json')))
            
            ## for pincode level data
            for z in d['data']['pincodes']:
                # print(z)
                Name=z['name']
                count=z['registeredUsers']
                # print(Name,count,amount)
                # print(year)
                data_dict['Level'].append('Pincode')
                data_dict['District_Pincode_Name'].append(Name) #appending type amount and count to defined dictionary
                data_dict['User_Registrd_Count'].append(count)
                data_dict['State'].append(i)
                data_dict['Year'].append(year)
                data_dict['Quarter'].append(int(k.strip('.json')))


### For State Level Files
folder_path_st_lvl=output_path+"/data/top/user/country/india/"

years_list=['2018','2019','2020','2021','2022','2023','2024']

for i in years_list:
    file_path=folder_path_st_lvl+i+"/"
    # print(file_path)
    try:
        agg_files=os.listdir(file_path)
        for k in agg_files:
                json_file=file_path+k  ## json file path
                # print(json_file)
                # print(file)
                data=open(json_file,'r')
                d=json.load(data)  
                # print(d)
            ### State level data
                for z in d['data']['states']:
                    # print(z)
                    Name=z['name']                    
                    count=z['registeredUsers']
                    # print(Name,count,amount)
                    # print(year)
                    data_dict['Level'].append('State')
                    data_dict['District_Pincode_Name'].append(Name) #appending type amount and count to defined dictionary
                    data_dict['User_Registrd_Count'].append(count)
                    data_dict['State'].append(Name)
                    data_dict['Year'].append(year)
                    data_dict['Quarter'].append(int(k.strip('.json')))
    except Exception as e:
        print('Error found',e)


## creating the dataframe
agg_df=pd.DataFrame(data_dict)

display(agg_df)

# #writing it to csv
agg_df.to_csv(f"{processed_data_path+'/'}{channel}_{data_type}_data.csv",index=False)

,State,Year,Quarter,Level,District_Pincode_Name,User_Registrd_Count
0,andaman-&-nicobar-islands,2018,1,District,south andaman,5846
1,andaman-&-nicobar-islands,2018,1,District,north and middle andaman,632
2,andaman-&-nicobar-islands,2018,1,District,nicobars,262
3,andaman-&-nicobar-islands,2018,1,Pincode,744103,1608
4,andaman-&-nicobar-islands,2018,1,Pincode,744101,1108
...,...,...,...,...,...,...
18571,tamil nadu,2024,4,State,tamil nadu,33966610
18572,bihar,2024,4,State,bihar,33345285
18573,madhya pradesh,2024,4,State,madhya pradesh,32876660
18574,telangana,2024,4,State,telangana,31726856
18575,andhra pradesh,2024,4,State,andhra pradesh,29984431

## Connecting to MySQL and Uploading Datasets

In [ ]:
 ## Setting up MySQL connection using sql alchemy
#loading environment varibles from .env files

host=os.getenv("my_sql_host")
# print(host)
user=os.getenv("my_sql_user")
password=os.getenv("my_sql_password")
port=3306
database='phonepe_pulse'
password = quote_plus(password)

## creating engine and connecting to sql database
print('Engine Created')
# engine.execute(f'create database if not exists {database}') this does not work as .execute is removed from sql alchemy
engine = create_engine(f'mysql+pymysql://{user}:{password}@{host}:{port}/')
with engine.begin() as conn:
    conn.execute(text(f"CREATE DATABASE IF NOT EXISTS `{database}`"))
print('Database Created')
engine.dispose() #closing the connection

## creatign new engine to push the datset to table
engine=create_engine(f'mysql+pymysql://{user}:{password}@{host}:{port}/{database}')

#### Pushing Dataframes to SQL Tables
file_paths=r'C:\Users\nagan\OneDrive\Desktop\Guvi\Project\PhonePe\Data Processing\Files\Processed_Data'

############## Aggregated Data Pushing #############################

## aggregated transaction data
agg_trans_data=pd.read_csv(f'{file_paths+"/"}aggregated_transaction_data.csv')

print(f'Dataframe is Created')

print('Pushing Data to SQL Table')
agg_trans_data.to_sql("aggregated_trans",con=engine,if_exists='replace',index=False)
print(f'Data Pushed to aggregated_trans table')


### Aggregated Insurance Data
data='insurance'
agg_trans_data=pd.read_csv(f'{file_paths+"/"}aggregated_{data}_data.csv')

print(f'Dataframe is Created')

print(f'Pushing Data to {data} SQL Table')
agg_trans_data.to_sql(f"aggregated_{data}",con=engine,if_exists='replace',index=False)
print(f'Data Pushed to  {data} table')


### Aggregated User Data
table='aggregated'
data='user'
agg_trans_data=pd.read_csv(f'{file_paths+"/"}{table}_{data}_data.csv')

print(f'Dataframe is Created')

print(f'Pushing Data to {data} SQL Table')
agg_trans_data.to_sql(f"{table}_{data}",con=engine,if_exists='replace',index=False)
print(f'Data Pushed to  {data} table')



####################### Map Data Pushing ############################
### Map trans Data
table='map'
data='transaction'
agg_trans_data=pd.read_csv(f'{file_paths+"/"}{table}_{data}_data.csv')

print(f'Dataframe is Created')

print(f'Pushing Data to {data} SQL Table')
agg_trans_data.to_sql(f"{table}_{data}",con=engine,if_exists='replace',index=False)
print(f'Data Pushed to  {data} table')

### Map insurance Data
table='map'
data='insurance'
agg_trans_data=pd.read_csv(f'{file_paths+"/"}{table}_{data}_data.csv')

print(f'Dataframe is Created')

print(f'Pushing Data to {data} SQL Table')
agg_trans_data.to_sql(f"{table}_{data}",con=engine,if_exists='replace',index=False)
print(f'Data Pushed to  {data} table')


### Map User Data
table='map'
data='user'
agg_trans_data=pd.read_csv(f'{file_paths+"/"}{table}_{data}_data.csv')

print(f'Dataframe is Created')

print(f'Pushing Data to {data} SQL Table')
agg_trans_data.to_sql(f"{table}_{data}",con=engine,if_exists='replace',index=False)
print(f'Data Pushed to  {data} table')


############# Top trans Data #################################
table='top'
data='transaction'
agg_trans_data=pd.read_csv(f'{file_paths+"/"}{table}_{data}_data.csv')

print(f'Dataframe is Created')

print(f'Pushing Data to {data} SQL Table')
agg_trans_data.to_sql(f"{table}_{data}",con=engine,if_exists='replace',index=False)
print(f'Data Pushed to  {data} table')

### Top insurance Data
table='top'
data='insurance'
agg_trans_data=pd.read_csv(f'{file_paths+"/"}{table}_{data}_data.csv')

print(f'Dataframe is Created')

print(f'Pushing Data to {data} SQL Table')
agg_trans_data.to_sql(f"{table}_{data}",con=engine,if_exists='replace',index=False)
print(f'Data Pushed to  {data} table')


### Top User Data
table='top'
data='user'
agg_trans_data=pd.read_csv(f'{file_paths+"/"}{table}_{data}_data.csv')

print(f'Dataframe is Created')

print(f'Pushing Data to {data} SQL Table')
agg_trans_data.to_sql(f"{table}_{data}",con=engine,if_exists='replace',index=False)
print(f'Data Pushed to  {data} table')

localhost
Engine Created
Database Created